name: Publish Docker Image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mohdrashid01/your-docker-image:latest
          registry: docker.pkg.github.com
          repository: mohdrashid01/your-github-packages-repo/your-docker-image
