name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
#        uses: actions/hello-world-docker-action@v2
        
      - name: Docker Image Status
        run: docker image ls
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
#          tags: mohdrashid01/your-docker-image:latest
          tags: mohdrashid01/build-push-action:latest
          registry: docker.pkg.github.com
          repository: mohdrashid01/your-github-packages-repo/your-docker-image
